### ISSUE TITLE
Updating the charm state from events inside containers

### ISSUE THREAD

**Issue by simonklb** [juju-solutions/layer-docker#54]
When dealing with Docker charms we have the docker.ready state which works great. However, when dealing with things going on inside the actual container it's not as easy.

The problem that prompted this issue was my inability to, in a nice way, make the charm go into a ready state when the service started inside Docker was done installing.

Right now there doesn't seem to be a better solution than continuously polling for the status of a service running inside a Docker container. But having poll-loops and setting a proper timeout value is messy.

Let's find a better solution for this!

**Comment by mbruzek** [comment]
Thanks @simonklb that is an interesting problem! And something that we have worked around with sleeps ourselves. 

Lets use this issue to brainstorm ideas:

I could envision the docker/juju library being extended to run `docker ps` and raise $NAME.ready where $NAME is the name in the docker container. This method could be run in a loop for a short amount of time (only because I don't know a good exit condition).

Any other ideas/suggestions?

**Comment by johnsca** [comment]
This is directly related to the exploratory work that @bcsaller is doing.

**Comment by simonklb** [comment]
@mbruzek Even checking docker ps wouldn't suffice since things can be going on inside the docker container that still isn't ready.

Would it be possible to let the application raise states from inside the container?

Possibly related: https://github.com/docker/docker/issues/21142

**Comment by llarsson** [comment]
I would also like a way to signal from within the container that the application is ready. 

An optimistic `sleep` for a given time period or output from `ps | grep application` are not sufficient: a complicated application such as a database might start its process (making it visible in `ps`) but be unable to handle requests until it has performed arbitrarily complex operations first (e.g. synchronizing data).

**Comment by chuckbutler** [comment]
Can I get someone to post a docker-compose based workload here that exhibits the behavior? i think i have one that will be suitable but its a bit of a schlog as it requires a docker-registry and then portus itself.. but it runs ~ 30 seconds of db-migrations on first boot due to how rails and active-record handle the ORM backend.

It would be good to have some baselines here that we can use to validate against as we continue exploring this topic.

I'd also like to hear from @bcsaller to see if this bug indeed overlaps with the work being done, i don't think "workload status" was necessarily one of them, but I'm not entirely certain, and it can probably be added if not.
