### ISSUE TITLE
docker-compose still ships from pypi

### ISSUE THREAD

**Issue by lazypower** [juju-solutions/layer-docker#98]
docker-compose being pulled from pypi in exec.d/docker-compose/charm-pre-install.sh limits the offlineability of this charm.

Prior work was done to stuff docker-compose into the wheelhouse. That may still be a viable option for delivery of docker-compose from layer docker.

**Comment by simonklb** [comment]
Just encountered a bug when deploying my Docker charm due to it being introduced into docker-py. Fixing this issue would eliminate the risk of that happening again since you would at least stick with the version that your charm was built with and not pull the latest version at each deployment.

@chuckbutler would you mind putting some prio on this?

**Comment by stub42** [comment]
This will affect CAAS charms, as it is recommended to use the docker layer.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809364.
